steps:
  - name: "node"
    entrypoint: "npm"
    args: [ 'install' ]
  - name: "gcr.io/cloud-builders/npm"
    entrypoint: "npx"
    args: [ 'nx', 'build', 'public-api', '--prod' ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '--build-arg',
        'SOURCE=cb-dev-298308',
        '-f',
        'apps/public-api/Dockerfile',
        '-t',
        'gcr.io/cb-dev-298308/loop-v3/public-api',
        '.'
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/cb-dev-298308/loop-v3/public-api' ]
  # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run',
        'deploy',
        'loop-pro-public-api',
        '--image',
        'gcr.io/cb-dev-298308/loop-v3/public-api',
        '--region',
        'europe-west1',
        '--platform',
        'managed',
        '--allow-unauthenticated'
      ]
    timeout: 1600s
timeout: 1600s
images:
  - 'gcr.io/cb-dev-298308/loop-v3/public-api'
